### ISSUE TITLE
Improving UI 

### ISSUE THREAD

**Issue by mlazana** [google/blockly-games#110]
So I was thinking of improving UI in order to be more user-friendly. (Considering that is mainly for kids )
I have the following ideas in mind:
 1. Change the dropdown list in index.html
 2. Change the view of about.html
 3. Change  the button "Blockly Games: ..." 
Using Javascript and CSS I think we could make blockly-games more attractive to users.
Do you think that is a good idea?  If yes, I am starting the implementation immediately!

**Comment by NeilFraser** [comment]
The three UI areas you highlighted are the three areas that are not intended for kids:

1. The language selector is important to be able to find and use, but is a distraction for students.  We actually want it to look ugly and boring, so that fewer students play around with it.
2. The about page is only intended for teachers and parents, so they can learn about the educational value of the games and how it might fit into their curriculum. This is one of the very few areas of Blockly Games that isn't translated into 50+ languages.
3. The navigation at the top of the page is a controversial element.  Some teachers wish it didn't exist, since it allows students to leave the track and skip around.  Some teachers like it since it allows faster students to skip past levels that they find too easy.  Our compromise is to include it, but try to avoid drawing attention to it.

I'm actually quite pleased that you listed those three areas.  It shows two things: First, that you have a great eye for spotting unappealing design.  Second, that our areas of intentionally unappealing designs are exactly where we intended them to be.  These are three rare cases where ugly design is actually the goal!

This situation is similar to Disney's use of a colour they refer to as "[Go Away Green](https://www.apartmenttherapy.com/paint-tricks-use-disneys-go-away-green-219276)".  It's a method to make people ignore certain objects.

Have you spotted any other areas in Blockly Games that could use improvement?

**Comment by MoonKingArthur** [comment]
Using the default sans-serif font, when there's so many great ones to choose from. Also, the change language button is styled kinda blandly. It should just be a solid color, like the `Clear data` button

**Comment by NeilFraser** [comment]
> Using the default sans-serif font, when there's so many great ones to choose from.

We found that specifying non-default fonts results is more text that looks like this "⌷⌷⌷⌷⌷⌷⌷⌷⌷" in non-western languages.
