### ISSUE TITLE
Maze just show button

### ISSUE THREAD

**Issue by viet1pro** [google/blockly-games#121]
All other can be run execpt Maze
The errror in console of Maze is:
```Uncaught TypeError: N.Ia is not a function```
But when i reload the page, the problem is resolve

**Comment by NeilFraser** [comment]
Two more pieces of information that would help:
* What's the exact URL of the page you are loading?
* Is this a repeatable error, or did it just appear one time?

**Comment by viet1pro** [comment]
I made a modification for my school at: https://dev.misblockly.tk/maze.html
This is a repeatable error.

**Comment by NeilFraser** [comment]
The problem is in https://dev.misblockly.tk/masterFunc.js  This file declares a global variable named `N` which collides with another global variable named `N` declared in https://dev.misblockly.tk/maze/generated/vi/compressed.js  Since masterFunc.js loads async, there is a race condition, sometimes it loads first (fine), sometimes not (crash).

Hope this helps!

**Comment by viet1pro** [comment]
Thanks :)
