### ISSUE TITLE
couldn't find the file  build/closurebuilder.py

### ISSUE THREAD

**Issue by lightnightlee** [google/blockly-games#72]

**Comment by lightnightlee** [comment]
I found the Make file. always couldn't find the url
svn checkout https://github.com/google/closure-library/trunk/closure/bin/build  build.
actually I didn't find the "trunk/closure", I only could find the "tree/master/closure..." path.
but after I changed to "tree/master" it also couldn't find it .
my network is good.
is there some typo here?

**Comment by NeilFraser** [comment]
Works for me:

```
> svn checkout https://github.com/google/closure-library/trunk/closure/bin/build build
A    build/closurebuilder.py
A    build/depstree.py
A    build/depstree_test.py
A    build/depswriter.py
A    build/depswriter_test.py
A    build/jscompiler.py
A    build/jscompiler_test.py
A    build/source.py
A    build/source_test.py
A    build/treescan.py
Checked out revision 7412.
>
```

I assume you are following the steps here:
https://github.com/google/blockly-games/wiki/Build

**Comment by bernardgisin** [comment]
Hello, 
I had the same problem as mentioned by "lightnightlee" ! 
The file "closurebuilder.py" and probably all the directory from "closure-library/closure/bin/build/" are missing in the "blockly-game/third-party" or "blockly-game-master/third-party" ! 
I downloaded the file : "google-closure-library-v20180910-190-ge52d9b5.zip" from the Web : "https://developers.google.com/blockly/guides/modify/web/closure", 
unzipped it and found the above mentioned "build" directory. 
I created the directory  : "blockly-game-master/third-party".
I copied the "closure-library/closure/bin/build" directory to : "blockly-game-master/third-party". 
I'm working on linux (KUbuntu 18.4) and had to install the two following apps :
sudo apt install wget 
sudo apt install subversion
Then I could type : 
make deps
I got to confirm 10 times with "r" the conflict :
"Arborescences en conflit sur 'build/closurebuilder.py' "
waited, and this time it worked through the end.
Then I typed : 
make en 
waited, and got the English version with the "compressed.js" and "uncompressed.js" files.
I got several WARNING such as :
"WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$2"

I did it three times to be sure that I didn't miss anything.

To start, I'm launching " appengine/index.html?lang=en ".

Since I'm french speaking, I tried to compile the french version with
make fr
But it says : "make: *** Aucune règle pour fabriquer la cible 'fr'. Arrêt."
in english  : "make: *** No rules to make the target 'fr'. Stop. "
I tried also :
make languages
make all
Without any success.

I modified the "Makefile" replacing all : "-en"  by  "-fr", all  "/en"  by  "/fr" and some more "en" by "fr", the once which were not in works. Then I typed :
make fr
I got "fr" folders, but the content was still in english !

I'm investigating further...
