### ISSUE TITLE
Blank game page on build.

### ISSUE THREAD

**Issue by baseljd** [google/blockly-games#75]
Hello team,

So I've been trying to build using the python file, but I've been getting the ECMA5 error that it should be ECMA6. I've already opened an issue regarding this. 

A Bypass I've found is changing ECMA5 to 6 in the build.py file; it worked! The only downside is that it generates a lot of errors. The index page that has all the games are run successfully but the maze doesn't run.

All of the games show a blank white page, or an index page showing all of the files contained. 
Note that I did run `make maze-en` and `make index-en`.

Any help?

**Comment by NeilFraser** [comment]
I've traced this down to the JavaScript compiler stripping off all the properties from Blockly.FieldDropdown.  In particular, 'fromJson', as well as 'CHECKMARK_OVERHANG' and 'MAX_MENU_HEIGHT'.  Why the ECMASCRIPT6_STRICT compiler is doing this is a mystery, one would think that ES6 would be backward compatible for things like this.

A work-around is to change two compiler arguments:
    '--compilation_level', 'SIMPLE',
    '--language_in', 'ECMASCRIPT6_STRICT',

Using 'SIMPLE' mode stops the compiler from tree-shaking.  It results in a much larger JS file (952 kb instead of 316 kb), but that's fine for local testing.

Waiting on ACE to rebuild their binaries, so that the ES5 path works again...
