### ISSUE TITLE
Dashboard Interface

### ISSUE THREAD

**Issue by alessiojr** [google/blockly-games#80]
Hello, I'm Alessandro professor at a public university in Brazil. We have a project with needy communities and we are using blockly-games to teach teens as an alternative to code.org.
Our students have volunteered to make a Dashboard that communicates with blockly-games for student management, such as code.org.
Is there a similar project? or is this Dashboard desirable?

**Comment by NeilFraser** [comment]
Google probably can't implement a dashboard due to legal reasons (GDPR, COPPA, etc).  That's why we have no logins, there's no names on the gallery, and our data-gathering is limited to a generic call to Google Analytics.

That said, Blockly Games is completely open source, so you could host your own instance on App Engine and create any dashboards you desire.  As far as I know, GDPR and COPPA would not apply to you in Brazil (disclaimer: I am not a lawyer).
